export const convertWeatherCodeToString = (weatherCode) => {
  const weatherCodes = {
    0: "Clear skies",
    1: "Partly cloudy",
    2: "Partly cloudy",
    3: "Overcast",
    4: "Partly cloudy",
    5: "Haze",
    10: "Mist",
    21: "Rain possible",
    22: "Snow possible",
    23: "Sleet possible",
    24: "Freezing drizzle",
    29: "Thundery outbreaks",
    38: "Blowing snow",
    39: "Blizzard",
    45: "Fog",
    48: "Freezing fog",
    49: "Freezing fog",
    50: "Light drizzle",
    51: "Light drizzle",
    52: "Drizzle",
    53: "Moderate drizzle",
    54: "Drizzle",
    55: "Heavy drizzle",
    56: "Freezing drizzle",
    57: "Heavy drizzle",
    60: "Light rain",
    61: "Rain",
    62: "Moderate rain",
    63: "Moderate rain",
    64: "Heavy rain",
    65: "Heavy rain",
    66: "Light freezing rain",
    67: "Heavy freezing rain",
    70: "Light snow",
    71: "Light snow",
    72: "Moderate snow",
    73: "Moderate snow",
    74: "Heavy snow",
    75: "Heavy snow",
    77: "Snow grains",
    79: "Ice pellets",
    80: "Rain showers",
    81: "Rain showers",
    82: "Heavy rain showers",
    83: "Sleet showers",
    84: "Sleet showers",
    85: "Snow showers",
    86: "Heavy snow showers",
    87: "Ice pellets",
    88: "Ice pellets",
    91: "Rain with thunder",
    92: "Rain with thunder",
    93: "Snow with thunder",
    94: "Snow with thunder",
    95: "Thunderstorm",
    96: "Thunderstorm with hail",
    99: "Thunderstorm with hail",
  };

  return weatherCodes[weatherCode] || "Unknown";
};
